version: 2

#  the tool for the documents
sphinx:
  configuration: docs/source/conf.py  # the path of Sphinx config files

# the python version of the documents
python:
  version: 3.8  # the python version
  install:
    - requirements: docs/requirements.txt  # requirements files
